### PR TITLE
Added Single instance Support

### LINKED ISSUE #95: Singleton QZ Tray Instance
Request to allow QZ Tray to be aware of other running instances and shut itself down.

### PR DESCRIPTION
**Pull request by Vzor-**
Closes #95

### CODE REVIEW

**Comment by tresf** [comment]
@bberenz (@robertcasto) any feedback on this prior to merging this feature is greatly appreciated.  Kyle added a `getProgramName` websocket request to support self-identification so that a full JSON message exchange wouldn't be needed.  If you feel this approach is bad, please recommend an alternative.

Also, we're only performing a check on insecure ports, since they're more consistently available and easier to connect to versus secure ports.

Last, we'll be porting this functionality to 2.0, so if there are any naming conventions or quality issues, please bring them up now so we can address.

**Comment by akberenz** [comment]
I don't see any issues with that approach, we do the same thing for our keep-alives.
The code looks good. One thing to be aware of for 2.0, is that secure and insecure ports are in separate arrays now so that it is easier to read (no longer index value +1).

**Comment by tresf** [comment]
Thanks @bberenz.  Will merge.

Can you port this code to 2.0 or shall we?

**Comment by akberenz** [comment]
I can take care of porting this to the 2.0 branch.

**Pull request merged**
